/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#f8f9ff',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#131b2e',
        'on-primary-container': '#7c839b',
        secondary: '#0051d5',
        'on-secondary': '#ffffff',
        'secondary-container': '#316bf3',
        'on-secondary-container': '#fefcff',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#261a00',
        'on-tertiary-container': '#a87d00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#45464d',
        'on-background': '#0b1c30',
        'surface-variant': '#d3e4fe',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#bec6e0',
        outline: '#76777d',
        'outline-variant': '#c6c6cd',
        'surface-tint': '#565e74',
        'primary-fixed': '#dae2fd',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3f465c',
        'secondary-fixed': '#dbe1ff',
        'secondary-fixed-dim': '#b4c5ff',
        'on-secondary-fixed': '#00174b',
        'on-secondary-fixed-variant': '#003ea8',
        'tertiary-fixed': '#ffdf9f',
        'tertiary-fixed-dim': '#f9bd22',
        'on-tertiary-fixed': '#261a00',
        'on-tertiary-fixed-variant': '#5c4300',
        'sidebar-bg': '#0f172a',
        'surface-bg': '#f8fafc',
        'border-subtle': '#e2e8f0',
        'text-on-dark': '#cbd5e1',
        'success-green': '#22c55e',
        'error-red': '#ef4444',
        'warning-amber': '#f59e0b',
        'ai-cyan': '#06b6d4',
      },
      fontFamily: {
        'display-lg': ['Ranade', 'Outfit', 'Poppins', 'sans-serif'],
        'headline-lg': ['Ranade', 'Outfit', 'Poppins', 'sans-serif'],
        'headline-md': ['Ranade', 'Outfit', 'Poppins', 'sans-serif'],
        'body-lg': ['Ranade', 'Inter', 'Outfit', 'sans-serif'],
        'body-md': ['Ranade', 'Inter', 'Outfit', 'sans-serif'],
        'body-sm': ['Ranade', 'Inter', 'Outfit', 'sans-serif'],
        'label-md': ['Ranade', 'Inter', 'Outfit', 'sans-serif'],
        'label-sm': ['Ranade', 'Inter', 'Outfit', 'sans-serif'],
        'caps-xs': ['Ranade', 'Inter', 'Outfit', 'sans-serif'],
        'caption': ['Ranade', 'Inter', 'Outfit', 'sans-serif'],
      },
      borderRadius: {
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}
