import type { CSSProperties, SVGProps } from 'react';
import {
  Pulse,
  Archive,
  ArrowClockwise,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowsClockwise,
  ArrowsCounterClockwise,
  ArrowsInSimple,
  ArrowsOutSimple,
  Bank,
  Bell,
  BellRinging,
  BellSlash,
  BookOpen,
  BracketsCurly,
  Brain,
  Broadcast,
  Bug,
  Buildings,
  Cake,
  Calendar,
  CalendarBlank,
  CalendarDots,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartBar,
  ChartDonut,
  ChartLine,
  ChartLineUp,
  ChartPie,
  ChatCircle,
  ChatCircleText,
  ChatDots,
  ChatsCircle,
  Check,
  CheckCircle,
  Checks,
  Circle,
  CircleNotch,
  Clipboard,
  ClipboardText,
  Clock,
  ClockCounterClockwise,
  Cloud,
  CloudArrowUp,
  Code,
  Copy,
  Cpu,
  Cross,
  Crosshair,
  Database,
  Desktop,
  Devices,
  DotsThree,
  DotsThreeVertical,
  DownloadSimple,
  Envelope,
  EnvelopeOpen,
  EnvelopeSimple,
  Eye,
  EyeSlash,
  FileDashed,
  FileText,
  FirstAidKit,
  Flame,
  FloppyDisk,
  FolderOpen,
  FolderStar,
  Gauge,
  GearSix,
  GitBranch,
  Hand,
  HardDrive,
  HardHat,
  Headset,
HandHeart,
  Hourglass,
  HourglassMedium,
  HourglassSimple,
  House,
  HouseLine,
  Hurricane,
  IdentificationBadge,
  ImageSquare,
  Images,
  Info,
Gavel,
  Key,
  LinkBreak,
  LinkSimple,
  List,
  ListChecks,
  ListNumbers,
  LockKey,
  LockSimple,
  Lightning,
  MagnifyingGlass,
  MagnifyingGlassPlus,
  MapPin,
  MapTrifold,
  Megaphone,
Microphone,
  Monitor,
  Moon,
  NavigationArrow,
  NotePencil,
  Package,
  Paperclip,
  PaperPlaneTilt,
  PawPrint,
  PencilSimple,
  PersonSimpleRun,
  Phone,
  PhoneCall,
  Play,
  PlayCircle,
  Plug,
  Plus,
  PlusCircle,
  PlusSquare,
  Printer,
  Prohibit,
  Question,
  Scan,
  Receipt,
  Robot,
  Scales,
  SealCheck,
  HardDrives,
  ShareNetwork,
  Shield,
  ShieldCheck,
  ShieldSlash,
  ShieldStar,
  SignIn,
  SignOut,
  Signpost,
  Siren,
  SlidersHorizontal,
  DeviceMobile,
  Sparkle,
  SpeakerHigh,
  Stack,
  Sun,
  SquaresFour,
  Table,
  Tag,
  Target,
  TerminalWindow,
  TextAa,
  TextAlignLeft,
  Timer,
  Toilet,
  TrafficCone,
  Tray,
  TrayArrowUp,
  TrendDown,
  TrendUp,
  Trash,
  Truck,
  UploadSimple,
  User,
  UserCircle,
  UserGear,
  UserMinus,
  UserPlus,
  Users,
  UsersThree,
  VideoCamera,
  Warning,
  WarningCircle,
  WarningOctagon,
  WifiHigh,
  Wrench,
  X,
  type Icon,
} from '@phosphor-icons/react';

export type PhWeight = 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone';

const PH_ICONS: Record<string, Icon> = {
  account_balance: Bank,
  account_circle: UserCircle,
  account_tree: GitBranch,
  add: Plus,
  add_alert: BellRinging,
  add_box: PlusSquare,
  add_circle: PlusCircle,
  add_photo_alternate: ImageSquare,
  admin_panel_settings: ShieldCheck,
  ambulance: FirstAidKit,
  analytics: ChartLine,
  apartment: Buildings,
  api: Code,
  archive: Archive,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  assignment: Clipboard,
  assignment_turned_in: ClipboardText,
  attach_file: Paperclip,
  attachment: Paperclip,
  audio: Microphone,
  auto_awesome: Sparkle,
  auto_transmission: GearSix,
  autorenew: ArrowClockwise,
  badge: IdentificationBadge,
  balance: Scales,
  bar_chart: ChartBar,
  block: Prohibit,
  bolt: Lightning,
  bug_report: Bug,
  build: Wrench,
  cake: Cake,
  calendar_month: CalendarBlank,
  calendar_today: Calendar,
  call: Phone,
  campaign: Megaphone,
  category: Tag,
  cell_tower: Broadcast,
  chat: ChatCircleText,
  chat_bubble: ChatCircle,
  check: Check,
  check_circle: CheckCircle,
  chevron_left: CaretLeft,
  chevron_right: CaretRight,
  close: X,
  cloud: Cloud,
  cloud_upload: CloudArrowUp,
  construction: HardHat,
  contact_phone: PhoneCall,
  content_copy: Copy,
  cyclone: Hurricane,
  dashboard: SquaresFour,
  dashboard_customize: SlidersHorizontal,
  dark_mode: Moon,
  data_object: BracketsCurly,
  data_usage: ChartDonut,
  database: Database,
  delete: Trash,
  description: FileText,
  desktop_windows: Desktop,
  devices: Devices,
  directions_run: PersonSimpleRun,
  dns: HardDrives,
  done_all: Checks,
  download: DownloadSimple,
  draft: FileDashed,
  edit: PencilSimple,
  edit_note: NotePencil,
  emergency: Siren,
  emergency_home: HouseLine,
  emergency_share: ShareNetwork,
  error: WarningCircle,
  expand_less: CaretUp,
  expand_more: CaretDown,
  family_restroom: UsersThree,
  folder_open: FolderOpen,
  folder_special: FolderStar,
  forum: ChatsCircle,
  fullscreen: ArrowsOutSimple,
  fullscreen_exit: ArrowsInSimple,
  gavel: Gavel,
  gpp_bad: ShieldSlash,
  group: Users,
  groups: UsersThree,
  hard_drive: HardDrive,
  help: Question,
  help_outline: Question,
  history: ClockCounterClockwise,
  history_edu: BookOpen,
  home: House,
  home_pin: MapPin,
  home_repair_service: Wrench,
  hourglass_empty: Hourglass,
  hourglass_top: HourglassSimple,
  inbox: Tray,
  info: Info,
  inventory_2: Package,
  key: Key,
  layers: Stack,
  light_mode: Sun,
  link: LinkSimple,
  link_off: LinkBreak,
  list_alt: ListNumbers,
  local_fire_department: Flame,
  local_hospital: FirstAidKit,
  local_police: ShieldCheck,
  local_shipping: Truck,
  location_on: MapPin,
  lock: LockSimple,
  lock_reset: LockKey,
  login: SignIn,
  logout: SignOut,
  lowercase: TextAa,
  mail: EnvelopeSimple,
  manage_accounts: UserGear,
  manage_search: MagnifyingGlass,
  map: MapTrifold,
  mark_email_read: EnvelopeOpen,
  mark_email_unread: Envelope,
  medical_services: Cross,
  memory: Cpu,
  menu: List,
  menu_book: BookOpen,
  mic: Microphone,
  monitor_heart: Monitor,
  monitoring: Pulse,
  more_horiz: DotsThree,
  more_vert: DotsThreeVertical,
  my_location: Crosshair,
  near_me: NavigationArrow,
  notification_important: BellRinging,
  notifications: Bell,
  notifications_active: BellRinging,
  notifications_off: BellSlash,
  open_in_new: ArrowSquareOut,
  pending: HourglassMedium,
  pending_actions: ListChecks,
  person: User,
  person_add: UserPlus,
  person_alert: WarningCircle,
  person_off: UserMinus,
  person_search: MagnifyingGlass,
  pets: PawPrint,
  phone: Phone,
  phone_forwarded: PhoneCall,
  phone_in_talk: PhoneCall,
  photo_camera: Camera,
  photo_library: Images,
  pie_chart: ChartPie,
  pin_drop: MapPin,
  play_arrow: Play,
  play_circle: PlayCircle,
  policy: ShieldCheck,
  print: Printer,
  priority_high: WarningCircle,
  progress_activity: CircleNotch,
  psychology: Brain,
  radar: Scan,
  receipt_long: Receipt,
  record_voice_over: Microphone,
  refresh: ArrowsClockwise,
  report: Warning,
  report_problem: WarningOctagon,
  restore: ClockCounterClockwise,
  route: Signpost,
  router: WifiHigh,
  save: FloppyDisk,
  schedule: Clock,
  search: MagnifyingGlass,
  security: Shield,
  send: PaperPlaneTilt,
  settings_input_component: Plug,
  shield: Shield,
  shield_person: ShieldStar,
  show_chart: ChartLineUp,
  smart_toy: Robot,
  smartphone: DeviceMobile,
  sms: ChatDots,
  speed: Gauge,
  summarize: TextAlignLeft,
  support_agent: Headset,
  table: Table,
  table_chart: ChartBar,
  task_alt: CheckCircle,
  terminal: TerminalWindow,
  timer: Timer,
  today: CalendarDots,
  touch_app: Hand,
  track_changes: Target,
  traffic: TrafficCone,
  trending_down: TrendDown,
  trending_up: TrendUp,
  tune: SlidersHorizontal,
  unarchive: TrayArrowUp,
  update: ArrowsCounterClockwise,
  upload: UploadSimple,
  verified: SealCheck,
  verified_user: SealCheck,
  video: VideoCamera,
  videocam: VideoCamera,
  visibility: Eye,
  visibility_off: EyeSlash,
  volume_up: SpeakerHigh,
  volunteer_activism: HandHeart,
  warning: Warning,
  wc: Toilet,
  zoom_in: MagnifyingGlassPlus,
};

export function Ph({
  name,
  weight = 'regular',
  className,
  style,
  ...rest
}: {
  name?: string | null;
  weight?: PhWeight;
  className?: string;
  style?: CSSProperties;
} & SVGProps<SVGSVGElement>) {
  const Glyph = (name && PH_ICONS[name]) || Circle;
  return <Glyph weight={weight} size="1em" className={className} style={{ verticalAlign: 'middle', ...style }} {...rest} />;
}

export default Ph;